[build]
  command = "python3 build.py"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.9"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
