#!/usr/bin/env python3
"""On-page SEO audit for content/videos/*.md — run before/after a content pass.

    python3 scripts/seo-audit.py            # summary + the posts that need work
    python3 scripts/seo-audit.py --all      # every post, one line each

Checks the things a build step can't fix for you, because they're about the prose:

  answer-first   the primary keyword shows up in the opening paragraph, and that
                 paragraph reads like an answer rather than a warm-up
  intro-length   opening paragraph is 40-90 words (long enough to answer, short
                 enough to be a snippet)
  dup-h2         the body doesn't open with an H2 that just repeats the H1
  h2-keyword     at least one H2 carries the primary keyword
  length         body is 350+ words
  meta           description is 120-165 characters
  faq            at least 3 FAQ entries

Interlinking, schema, breadcrumbs and topic hubs are generated by build.py and
are deliberately NOT audited here.
"""
import os, re, sys, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VDIR = os.path.join(ROOT, "content", "videos")

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required:  pip install -r requirements.txt")

# Openers that delay the answer instead of giving it.
WARMUP = re.compile(
    r"^(in this video|in this episode|welcome|today we|we take a look|have you ever|"
    r"let's take|join us|ever wondered|if you)\b", re.I)


def blocks_of(body):
    return [b.strip() for b in re.split(r"\n\s*\n", body.strip()) if b.strip()]


def audit(path):
    raw = open(path, encoding="utf8").read()
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", raw, re.S)
    if not m:
        return {"slug": os.path.basename(path)[:-3], "issues": ["no-frontmatter"]}
    fm = yaml.safe_load(m.group(1)) or {}
    body = m.group(2).strip()
    blocks = blocks_of(body)
    paras = [b for b in blocks if not b.startswith("#")]
    intro = paras[0] if paras else ""
    pk = (fm.get("primary_keyword") or "").strip()
    desc = (fm.get("description") or "").strip()
    h2s = [b[3:].strip() for b in blocks if b.startswith("## ")]
    words = len(body.split())
    intro_words = len(intro.split())

    issues = []
    if not pk:
        issues.append("no-primary-keyword")
    elif pk.lower() not in intro.lower():
        issues.append("answer-first: primary keyword missing from opening paragraph")
    if WARMUP.match(intro):
        issues.append("answer-first: opening paragraph starts with a warm-up, not an answer")
    if intro_words and not (40 <= intro_words <= 90):
        issues.append(f"intro-length: {intro_words} words (want 40-90)")
    if blocks and blocks[0].startswith("## "):
        issues.append("dup-h2: body opens with an H2 that repeats the H1")
    if pk and not any(pk.lower() in h.lower() for h in h2s):
        issues.append("h2-keyword: no H2 contains the primary keyword")
    if words < 350:
        issues.append(f"length: {words} words (want 350+)")
    if not (120 <= len(desc) <= 165):
        issues.append(f"meta: description is {len(desc)} chars (want 120-165)")
    if len(fm.get("faq") or []) < 3:
        issues.append(f"faq: only {len(fm.get('faq') or [])} entries (want 3+)")
    return {"slug": os.path.basename(path)[:-3], "title": fm.get("title", ""),
            "words": words, "issues": issues}


def main():
    show_all = "--all" in sys.argv
    as_json = "--json" in sys.argv
    rows = [audit(os.path.join(VDIR, fn)) for fn in sorted(os.listdir(VDIR)) if fn.endswith(".md")]
    if as_json:
        print(json.dumps(rows, indent=2))
        return
    counts = {}
    for r in rows:
        for i in r["issues"]:
            counts[i.split(":")[0]] = counts.get(i.split(":")[0], 0) + 1
    clean = [r for r in rows if not r["issues"]]
    print(f"{len(rows)} posts — {len(clean)} clean, {len(rows) - len(clean)} need work\n")
    for k, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        print(f"  {n:>4}  {k}")
    print()
    for r in rows:
        if r["issues"] or show_all:
            print(f"{r['slug']}  ({r['words']}w)")
            for i in r["issues"]:
                print(f"    - {i}")


if __name__ == "__main__":
    main()
